<a href="https://colab.research.google.com/github/veenachowdaryayyannagari/veena/blob/main/cgpa_lpa_reg.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
df=pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]],columns=['cgpa','resume_score','lpa'])
df

cgpa  resume_score  lpa
0     8             8    4
1     7             9    5
2     6            10    6
3     5            12    7

In [ ]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [ ]:
model =Sequential()
model.add(Dense(2,activation='linear',input_dim=2))
model.add(Dense(1,activation='linear'))
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 2)                 6         
                                                                 
 dense_1 (Dense)             (None, 1)                 3         
                                                                 
Total params: 9 (36.00 Byte)
Trainable params: 9 (36.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:
optimizer=keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='mean_squared_error',optimizer=optimizer)
model.fit(df.iloc[:,0:-1].values,df['lpa'].values,epochs=75,verbose=1,batch_size=1)

Epoch 1/75
4/4 [==============================] - 0s 3ms/step - loss: 0.0517
Epoch 2/75
4/4 [==============================] - 0s 2ms/step - loss: 0.0448
Epoch 3/75
4/4 [==============================] - 0s 2ms/step - loss: 0.0439
Epoch 4/75
4/4 [==============================] - 0s 2ms/step - loss: 0.0422
Epoch 5/75
4/4 [==============================] - 0s 3ms/step - loss: 0.0421
Epoch 6/75
4/4 [==============================] - 0s 3ms/step - loss: 0.0418
Epoch 7/75
4/4 [==============================] - 0s 3ms/step - loss: 0.0418
Epoch 8/75
4/4 [==============================] - 0s 3ms/step - loss: 0.0420
Epoch 9/75
4/4 [==============================] - 0s 2ms/step - loss: 0.0415
Epoch 10/75
4/4 [==============================] - 0s 3ms/step - loss: 0.0423
Epoch 11/75
4/4 [==============================] - 0s 3ms/step - loss: 0.0409
Epoch 12/75
4/4 [==============================] - 0s 3ms/step - loss: 0.0413
Epoch 13/75
4/4 [==============================] - 0s 2ms/step - loss: 0.

In [ ]:
model.get_weights()

[array([[-0.04243146,  0.25842983],
        [-0.466001  , -0.95351243]], dtype=float32),
 array([-0.22068614, -0.1907008 ], dtype=float32),
 array([[-0.33715832],
        [-0.46735907]], dtype=float32),
 array([0.16578382], dtype=float32)]